language: rust
rust:
  - stable
  - beta
  - nightly

script:
  # Test and build the Rust code.
  - cd rust_src
  - cargo test
  - cargo build
  - cd ..

  # Configure Emacs for building
  - ./autogen.sh
  # TODO: set up makeinfo on travis.
  - ./configure --without-makeinfo --with-xpm=no --with-gif=no
  - make -j 3

  - make check || echo 'make check failed'

notifications:
  fast_finish: true
  email: false

matrix:
  allow_failures:
    - rust: nightly

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
