---
language: rust

# Checkout only the top of the tree for expediency.
git:
  depth: 1
  quiet: true
  submodules: false

cache: cargo

addons:
  apt:
    packages:
      - texinfo
      - libgif-dev
      - libxmp-dev
      - libgnutls28-dev
  homebrew:
    packages:
    - gnutls
    - texinfo

jobs:
  include:
    - name: rustfmt
      os: linux
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt
      script: ./.travis-format.sh
