---
language: rust

# Checkout only the top of the tree for expediency.
git:
  depth: 1
  quiet: true
  submodules: false

cache: cargo

jobs:
  include:
    - name: rustfmt
      os: linux  # No need to run this everywhere
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt
      script: ./.travis-format.sh
    - name: clippy
      os: linux  # No need to run this everywhere
      addons:
        apt:
          packages:
            - libgif-dev
            - libxmp-dev
            - libgnutls28-dev
            - libxpm-dev
            - libgtk-3-dev  # Ensures clippy runs against the window system code
      before_script:
        - travis_wait rustup component add clippy
        - cargo clippy -- --version
        # Configuration is needed so the C <-> Rust connections are setup.
        - ./autogen.sh && ./configure --without-makeinfo
      script:
        - make clippy
    - name: test-linux-no-windows
      os: linux
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
        - RUST_BACKTRACE=1
        - RUSTFLAGS="-Dwarnings"
        - WERROR_CFLAGS="-Werror"
      script:
        - rustc --version
        - ./autogen.sh
        - ./configure --enable-checking=glyphs --without-makeinfo  --with-x=no --without-gconf --without-gsettings
        - make -j 3
        - echo '==> Running tests'
        - make check

notifications:
  fast_finish: true
  email: false

matrix:
  fast_finish: true
