language: rust
cache: cargo
rust:
  - nightly

# Run rustfmt first.
stages:
  - rustfmt
  - test

jobs:
  include:
    - stage: rustfmt
      os: linux  # No need to run this everywhere
      before_script:
        - travis_wait rustup install nightly-2017-10-22
        - rustup default nightly-2017-10-22
        # rustfmt doesn't know where to look for libraries yet.
        # See https://github.com/rust-lang-nursery/rustfmt/issues/1707#issuecomment-310005652
        - export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH
        # Install rustfmt-nightly 0.2.12 if it isn't already installed on
        # Travis. This can be slow to install, so raise the Travis timeout.
        - (which rustfmt && rustfmt --version && [[ "$(rustfmt --version)" =~ "0.2.9" ]]) || travis_wait cargo install --force rustfmt-nightly --vers 0.2.9
      script: ./.travis-format.sh
    - &FULL_TEST
        stage: test
        env:
          # Ensure that we build without warnings.
          - CARGO_FLAGS="--features 'strict'"
        os: linux
        addons:
          apt:
            packages:
              - texinfo
              - libgif-dev
              - libxpm-dev
        before_script:
          - if [ $TRAVIS_OS_NAME = linux ]; then ./autogen.sh && ./configure; fi
          # TODO: add the necessary dependencies so we can use the same configure flags on OS X.
          - if [ $TRAVIS_OS_NAME = osx ]; then ./autogen.sh && ./configure --without-makeinfo --with-xpm=no --with-gif=no --with-gnutls=no; fi
        script:
          - make -j 3 && echo '==> Running tests' && make check
    -
      <<: *FULL_TEST
      os: osx
    - &NO_WINDOW_SYSTEM_TEST
        stage: test
        env:
          # Ensure that we build without warnings.
          - CARGO_FLAGS="--features 'strict'"
          - TRAVIS_WITH_NO_WINDOW_SYSTEM=1  # So we can tell them apart
          - TRAVIS_ALLOW_FAILURE=1
        os: linux
        addons:
          apt:
            packages:
              - texinfo
        before_script:
          - if [ $TRAVIS_OS_NAME = linux ]; then ./autogen.sh && ./configure --without-makeinfo --with-x=no --without-gconf --without-gsettings; fi
          # TODO: add the necessary dependencies so we can use the same configure flags on OS X.
          - if [ $TRAVIS_OS_NAME = osx ]; then ./autogen.sh && ./configure --without-makeinfo --with-gnutls=no --with-x=no --without-gconf --without-gsettings; fi
        script:
          - make -j 3 && echo '==> Running nowindow tests' && make check
    -
      <<: *NO_WINDOW_SYSTEM_TEST
      os: osx
  allow_failures:
    - env: TRAVIS_ALLOW_FAILURE=1

notifications:
  fast_finish: true
  email: false
