---
language: rust

# Checkout only the top of the tree for expediency.
git:
  depth: 1
  quiet: true
  submodules: false

cache: cargo

jobs:
  include:
    - name: test-linux-no-windows
      os: linux
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
        - RUST_BACKTRACE=1
        - RUSTFLAGS="-Dwarnings"
        - WERROR_CFLAGS="-Werror"
      script:
        - rustc --version

notifications:
  fast_finish: true
  email: false

matrix:
  fast_finish: true
