---
language: rust

# Checkout only the top of the tree for expediency.
git:
  depth: 1
  quiet: true
  submodules: false

cache: cargo

jobs:
  include:
    - name: rustfmt
      os: linux  # No need to run this everywhere
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt
      script: ./.travis-format.sh
    - name: clippy
      os: linux  # No need to run this everywhere
      addons:
        apt:
          packages:
            - texinfo
            - libgif-dev
            - libxmp-dev
            - libgnutls28-dev
            - libgtk-3-dev  # Ensures clippy runs against the window system code
      before_script:
        - travis_wait rustup component add clippy
        # Configuration is needed so the C <-> Rust connections are setup.
        - ./autogen.sh && ./configure --without-makeinfo
      script:
        - make clippy
