name: Linux no GUI build

on:
  pull_request:
    # paths:
    # - 'lib/**'
    # - 'lib-src/**'
    # - 'src/**'
    # - 'rust_src/**'

jobs:
  linux-no-gui-build:
    name: Linux no GUI build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup Rust version
      run: rustup toolchain install $(cat rust-toolchain)
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --without-makeinfo --with-x=no --without-gconf --without-gsettings
    - name: make
      run: make -j 3
    - name: make check
      run: make check
